languageCode = "es-pe"
title = "ContraFrases"
baseurl = "http://contrafrases.com/"
theme = "ghostwriter"
googleAnalytics = "XXX"

[Author]
    name = "hdanniel"
    profile = "http://twitter.com/contrafrases"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "ContraFrases"
    description = "Frases mal citadas, ap√≥crifas, que nunca se dijeron. Falsas."
    github = "https://github.com/hdanniel/contrafrases.com"
    twitter = "https://twitter.com/contrafrases"
    opengraph = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"


